language: node_js
node_js:
- '6'
before_script:
- openssl aes-256-cbc -pass "pass:$TRAVIS_CI_SECRET" -in ./XeroAPI/xero-node/test/config/travis-ci -out ./XeroAPI/xero-node/test/config/nodejs-private.pem -d -a